const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const categoryMeta={english:{name:'English',color:'purple',desc:'Words, phrases and practice'},photography:{name:'Photography',color:'cyan',desc:'Frames, light and technique'},creativity:{name:'Creativity',color:'pink',desc:'Ideas, sketches and concepts'},custom:{name:'Custom',color:'orange',desc:'Anything uniquely yours'},book:{name:'Book',color:'cyan',desc:'Finished reading'}};
const STORAGE_ITEMS='evidence-items-v3',STORAGE_BOOKS='evidence-books-v3';
let items=JSON.parse(localStorage.getItem(STORAGE_ITEMS)||'[]'),books=JSON.parse(localStorage.getItem(STORAGE_BOOKS)||'[]');
let viewDate=new Date(2026,7,1),filter='all',selectedDate=null,selectedBook=null,currentPage='calendar';
const UI_STORAGE='evidence-ui-v1';let uiSettings={glow:true,motion:true,...JSON.parse(localStorage.getItem(UI_STORAGE)||'{}')};
const esc=value=>String(value??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const svg=id=>`<svg><use href="#${id}"/></svg>`;
const save=()=>{localStorage.setItem(STORAGE_ITEMS,JSON.stringify(items));localStorage.setItem(STORAGE_BOOKS,JSON.stringify(books))};
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('evidence-assets',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('images'))r.result.createObjectStore('images')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function storeAsset(key,data){if(!data)return;const db=await dbPromise;db.transaction('images','readwrite').objectStore('images').put(data,key)}
function readFile(file){return new Promise(resolve=>{if(!file)return resolve('');const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})}
function monthKey(){return `${viewDate.getFullYear()}-${String(viewDate.getMonth()+1).padStart(2,'0')}`}
function dateKey(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function monthItems(){return items.filter(x=>x.category!=='book'&&x.date.startsWith(monthKey()))}

function renderCalendar(){
 const y=viewDate.getFullYear(),m=viewDate.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,count=new Date(y,m+1,0).getDate(),prevCount=new Date(y,m,0).getDate();
 $('#monthTitle').innerHTML=`<span>${viewDate.toLocaleString('en',{month:'long'}).toUpperCase()}</span><small>${y}</small>`;
 const grid=$('#calendarGrid');grid.innerHTML='';
 for(let index=0;index<42;index++){
  let day=index-first+1,month=m,year=y,other=false;if(day<1){day+=prevCount;month--;other=true;if(month<0){month=11;year--}}else if(day>count){day-=count;month++;other=true;if(month>11){month=0;year++}}
  const key=dateKey(year,month,day),all=items.filter(x=>x.date===key),visible=all.filter(x=>filter==='all'||x.category===filter),photos=visible.filter(x=>x.photo).slice(0,3),photo=photos[0];
  const englishPreview=!photo&&visible.find(x=>x.category==='english'),primary=visible[0]?.category||'';const button=document.createElement('button');button.className=`day${other?' other':''}${visible.length?' evidence-day primary-'+primary:''}${photo?' has-photo':''}${photos.length>1?' collage':''}${englishPreview?' has-text':''}${selectedDate===key?' selected':''}`;button.dataset.date=key;button.innerHTML=`<span>${day}</span>${photos.length?`<span class="memory-stack">${photos.map((x,i)=>`<i style="--memory:url('${x.photo}');--layer:${i}"></i>`).join('')}</span>`:''}${englishPreview?`<em class="day-preview">${esc(englishPreview.title).slice(0,28)}</em>`:''}${visible.length?`<span class="dots">${[...new Set(visible.map(x=>x.category))].slice(0,4).map(c=>`<i class="${categoryMeta[c].color}"></i>`).join('')}</span><small>${visible.length} ${visible.length===1?'piece':'pieces'}</small>`:''}`;
  button.onclick=()=>{selectedDate=key;renderCalendar();openEvidence(key)};grid.appendChild(button);
 }
 const storyItems=items.filter(x=>x.date.startsWith(`${y}-${String(m+1).padStart(2,'0')}`));$('#monthStory').classList.toggle('visible',storyItems.length===0);
 renderNumbers();
}
function renderNumbers(){
 const list=monthItems(),active=new Set(list.map(x=>x.date)).size,categories=['english','photography','creativity','custom'],counts=Object.fromEntries(categories.map(c=>[c,list.filter(x=>x.category===c).length]));
 $('#totalEvidence').textContent=list.length;$('#activeDays').textContent=active;$('#usedCategories').textContent=categories.filter(c=>counts[c]).length;$('#booksRead').textContent=books.filter(b=>b.date.startsWith(monthKey())).length;
 categories.forEach(c=>$(`#${c}Count`).textContent=counts[c]);const total=list.length||1;let stops=[],sum=0;for(const c of categories){const start=sum/total*100;sum+=counts[c];stops.push(`var(--${categoryMeta[c].color}) ${start}% ${sum/total*100}%`)}$('#donut').style.background=list.length?`radial-gradient(circle,#f1f2f9 53%,transparent 55%),conic-gradient(${stops.join(',')})`:'radial-gradient(circle,#f1f2f9 53%,transparent 55%),conic-gradient(#dfe3ee 0 100%)';
 const dates=[...new Set(list.map(x=>x.date))].sort().reverse();let streak=0;if(dates.length){let d=new Date(dates[0]+'T12:00:00');for(const key of dates){if(key===d.toISOString().slice(0,10)){streak++;d.setDate(d.getDate()-1)}else break}}$('#streakCount').textContent=streak;$('.streak p').textContent=streak?'Keep it going!':'Start your first streak!';
 $('#miniBars').innerHTML=Array.from({length:10},(_,i)=>`<i style="height:${list.length?18+((i*17+list.length*9)%72):8+i*2}%"></i>`).join('');
}
function renderBooks(){
 $('#bookCount').textContent=`${books.length} ${books.length===1?'book':'books'} read this year`;const shelf=$('#bookshelf'),detail=$('#bookDetail');
 if(!books.length){shelf.innerHTML='<div class="empty-shelf"><b>Your shelf is waiting</b><span>Add your first finished book</span></div>';detail.innerHTML='';renderLibrary();return}
 selectedBook=selectedBook||books.at(-1).id;const shown=books.slice(-4);shelf.innerHTML=shown.map(b=>`<button class="book-cover ${b.id===selectedBook?'active':''}" data-book="${b.id}" ${b.cover?`style="background-image:url('${b.cover}')"`:''}>${b.cover?'':esc(b.title)}</button>`).join('');$$('[data-book]').forEach(b=>b.onclick=()=>{selectedBook=Number(b.dataset.book);renderBooks()});const b=books.find(x=>x.id===selectedBook)||books.at(-1);detail.className='book-detail';detail.innerHTML=`<h3>${esc(b.title)}</h3><p>${esc(b.author)}</p><div class="rating">${'★'.repeat(b.rating)}${'☆'.repeat(5-b.rating)}<b>${b.rating}.0</b></div><div class="finished">${svg('calendar')} Finished: ${formatDate(b.date)}</div><p class="book-note"><b>My note</b><br>${esc(b.note||'No note yet.')}</p>`;renderLibrary();
}
function renderRecent(){const recent=$('#recentList'),data=items.slice().sort((a,b)=>b.id-a.id).slice(0,4);if(!data.length){recent.innerHTML='<div class="empty-recent"><i>✦</i><b>No evidence yet</b><span>Your latest wins will appear here</span></div>';return}recent.innerHTML=data.map(x=>`<div class="recent-item"><i class="recent-icon">${x.category==='english'?'EN':x.category==='photography'?'◉':x.category==='book'?'▤':'✦'}</i><span><b>${esc(x.title)}</b><small>${categoryMeta[x.category]?.name.toUpperCase()||'EVIDENCE'}</small></span><button data-open="${x.id}">${svg('arrow')}</button></div>`).join('')}
function renderLibrary(){const grid=$('#libraryGrid');if(!grid)return;const q=$('#librarySearch')?.value.trim().toLowerCase()||'',year=$('#yearFilter')?.value||'all',sort=$('#bookSort')?.value||'newest';let data=books.filter(b=>(b.title+' '+b.author).toLowerCase().includes(q)&&(year==='all'||b.date.startsWith(year)));data.sort((a,b)=>sort==='rating'?b.rating-a.rating:sort==='title'?a.title.localeCompare(b.title):b.date.localeCompare(a.date));grid.innerHTML=data.length?data.map(b=>`<article class="library-card"><div class="library-art" ${b.cover?`style="background-image:url('${b.cover}')"`:''}>${b.cover?'':esc(b.title)}</div><h3>${esc(b.title)}</h3><p>${esc(b.author)}</p><div class="rating">${'★'.repeat(b.rating)}${'☆'.repeat(5-b.rating)}</div></article>`).join(''):emptyMarkup('▤','Your library is empty','Finished books will become part of your visual story.','ADD BOOK','empty-book');}
function formatDate(value){return new Date(value+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
function emptyMarkup(icon,title,text,button='ADD EVIDENCE',cls='empty-add'){return `<div class="empty-state glass"><i>${icon}</i><h2>${title}</h2><p>${text}</p><button class="neon-btn ${cls}">${svg('plus')}${button}</button></div>`}

function showPage(page){
 currentPage=page;$$('.page').forEach(p=>p.classList.remove('active'));$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
 if(page==='calendar'){$('#calendarPage').classList.add('active');renderCalendar();return}if(page==='library'){$('#libraryPage').classList.add('active');renderLibrary();return}
 $('#sectionPage').classList.add('active');$('#sectionTitle').textContent=page.toUpperCase();renderSection(page);
}
function renderSection(page){
 const root=$('#sectionContent');
 if(page==='timeline'){renderTimeline();return}
 if(page==='statistics'){const data=items.filter(x=>x.category!=='book'),days=new Set(data.map(x=>x.date)).size;root.innerHTML=`<div class="metric-grid"><article class="metric glass"><small>TOTAL EVIDENCE</small><strong>${data.length}</strong><span>pieces collected</span></article><article class="metric glass"><small>ACTIVE DAYS</small><strong>${days}</strong><span>days with progress</span></article><article class="metric glass"><small>BOOKS FINISHED</small><strong>${books.length}</strong><span>in your library</span></article></div>${!data.length?emptyMarkup('⌁','Your patterns will appear here','Collect evidence to unlock meaningful statistics.'):''}`;return}
 if(page==='categories'){const cats=['english','photography','creativity','custom'];root.innerHTML=`<div class="category-grid">${cats.map(c=>`<button class="category-card glass ${filter===c?'chosen':''}" data-category="${c}"><i class="${categoryMeta[c].color}"></i><span><b>${categoryMeta[c].name}</b><small>${categoryMeta[c].desc}</small></span><strong>${items.filter(x=>x.category===c).length}</strong></button>`).join('')}</div>`;return}
 root.innerHTML=`<div class="settings-card glass"><h2>Interface settings</h2><button class="switch ${uiSettings.glow?'on':''}" data-setting="glow"><span>Neon accents</span><i></i></button><button class="switch ${uiSettings.motion?'on':''}" data-setting="motion"><span>Interface animations</span><i></i></button><p>Your evidence and images stay in this browser. Nothing is sent to a server.</p></div>`;
}
function renderTimeline(query=''){const root=$('#sectionContent'),q=query.toLowerCase(),data=items.filter(x=>(x.title+' '+(x.note||'')+' '+(categoryMeta[x.category]?.name||'')).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);const search=`<label class="timeline-search glass">${svg('search')}<input id="timelineSearch" value="${esc(query)}" placeholder="Search your evidence"></label>`;root.innerHTML=search+(data.length?`<div class="timeline-list">${data.map(x=>`<article class="timeline-entry glass"><i class="${categoryMeta[x.category]?.color||'purple'}"></i><div><small>${formatDate(x.date)}</small><h3>${esc(x.title)}</h3><p>${categoryMeta[x.category]?.name.toUpperCase()||'EVIDENCE'}</p></div><div class="entry-actions">${x.category!=='book'?`<button data-edit="${x.id}">${svg('edit')}</button>`:''}<button data-delete="${x.id}">${svg('trash')}</button></div></article>`).join('')}</div>`:emptyMarkup(q?'⌕':'◷',q?'Nothing found':'Your timeline is empty',q?'Try a different phrase.':'Every small win will build a visible trail here.'));const input=$('#timelineSearch');input.oninput=()=>{const pos=input.selectionStart,value=input.value;renderTimeline(value);const next=$('#timelineSearch');next.focus();next.setSelectionRange(pos,pos)}}
function openEvidence(dateValue,item=null){const form=$('#evidenceForm');form.reset();form.elements.date.value=dateValue||new Date().toISOString().slice(0,10);form.elements.id.value=item?.id||'';form.elements.category.value=item?.category||'english';form.elements.title.value=item?.title||'';form.elements.note.value=item?.note||'';$('#evidenceModalTitle').textContent=item?'Edit Evidence':'Add Evidence';openModal($('#evidenceModal'))}
function openModal(modal){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function showToast(text){$('#toast span').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2100)}

$('#prevMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);selectedDate=null;renderCalendar()};$('#nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);selectedDate=null;renderCalendar()};$('#addEvidence').onclick=()=>openEvidence(dateKey(viewDate.getFullYear(),viewDate.getMonth(),1));$$('.section-add').forEach(b=>b.onclick=()=>openEvidence(new Date().toISOString().slice(0,10)));$$('.add-book').forEach(b=>b.onclick=()=>openModal($('#bookModal')));$('#categoryShortcut').onclick=()=>showPage('categories');$('#searchButton').onclick=()=>{showPage('timeline');setTimeout(()=>$('#timelineSearch')?.focus(),50)};
$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCalendar()});$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('.close-modal').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal-layer')));$$('.modal-layer').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m)});$('.user').onclick=()=>showToast('WELCOME, GALINA');
$('#librarySearch').oninput=renderLibrary;$('#yearFilter').onchange=renderLibrary;$('#bookSort').onchange=renderLibrary;
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),open=e.target.closest('[data-open]'),cat=e.target.closest('[data-category]'),setting=e.target.closest('[data-setting]');if(edit){const item=items.find(x=>x.id===Number(edit.dataset.edit));if(item)openEvidence(item.date,item)}if(del){const id=Number(del.dataset.delete);items=items.filter(x=>x.id!==id);books=books.filter(x=>x.evidenceId!==id);save();renderAll();renderSection(currentPage);showToast('ENTRY DELETED')}if(open)showPage('timeline');if(cat){filter=cat.dataset.category;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));showPage('calendar')}if(setting){const key=setting.dataset.setting;uiSettings[key]=!uiSettings[key];localStorage.setItem(UI_STORAGE,JSON.stringify(uiSettings));applyUiSettings();setting.classList.toggle('on',uiSettings[key]);showToast(key==='motion'?(uiSettings.motion?'ANIMATIONS ON':'ANIMATIONS OFF'):(uiSettings.glow?'NEON ON':'NEON OFF'))}if(e.target.closest('.empty-add'))openEvidence(new Date().toISOString().slice(0,10));if(e.target.closest('.empty-book'))openModal($('#bookModal'))});
$('#evidenceForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=Number(f.get('id'))||Date.now(),existing=items.find(x=>x.id===id),photo=await readFile(f.get('photo'));await storeAsset(`evidence-${id}`,photo);const record={id,date:f.get('date'),category:f.get('category'),title:f.get('title').trim(),note:f.get('note').trim(),photo:photo||existing?.photo||''};if(existing)items=items.map(x=>x.id===id?record:x);else items.push(record);save();closeModal($('#evidenceModal'));renderAll();if(currentPage!=='calendar')renderSection(currentPage);showToast(existing?'EVIDENCE UPDATED':'EVIDENCE SAVED')};
$('#bookForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=Date.now(),cover=await readFile(f.get('cover'));await storeAsset(`book-${id}`,cover);const evidenceId=id+1,book={id,evidenceId,title:f.get('title').trim(),author:f.get('author').trim(),date:f.get('date'),rating:Number(f.get('rating')),note:f.get('note').trim(),cover};books.push(book);items.push({id:evidenceId,date:book.date,category:'book',title:`Finished: ${book.title}`,note:book.note,photo:cover});selectedBook=id;save();e.currentTarget.reset();closeModal($('#bookModal'));renderAll();showToast('BOOK ADDED TO LIBRARY')};
function applyUiSettings(){document.body.classList.toggle('reduce-glow',!uiSettings.glow);document.body.classList.toggle('reduce-motion',!uiSettings.motion)}
function attachLightTracking(){const panels=$$('.dashboard,.books-card,.recent-card,.numbers-card,.motivation');panels.forEach(panel=>{panel.onpointermove=e=>{const r=panel.getBoundingClientRect();panel.style.setProperty('--mx',`${e.clientX-r.left}px`);panel.style.setProperty('--my',`${e.clientY-r.top}px`);panel.classList.add('light-active')};panel.onpointerleave=()=>panel.classList.remove('light-active')})}
function renderAll(){renderCalendar();renderBooks();renderRecent();attachLightTracking()}applyUiSettings();renderAll();
